services:
  api:
    build: .
    container_name: api
    volumes:
      - ./src:/src:ro
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PYTHONPATH: /src/api/
    depends_on:
      - db
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  
  db:
    image: postgres:16 # It's best to use a specific version instead of 'latest'
    container_name: pg-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data # Mount the named volume
  
volumes:
  pg-data: